<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>Kobold.ScreenGeometryCheck</AssemblyName>
    <RootNamespace>Kobold.ScreenGeometryCheck</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="WindowsBase" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Kobold.csproj" />
  </ItemGroup>
</Project>
